name: remove kind command
on:
  repository_dispatch:
    types: [remove-kind-command]
jobs:
  remove-kind:
    runs-on: ubuntu-latest
    steps:
      - uses: mkimuram/test-gha/plugins/remove-kind@main
