# Usage: | `/close` | `/close` | Closes an issue or PR. |
name: close command
on:
  repository_dispatch:
    types: [close-command]
jobs:
  close:
    runs-on: ubuntu-latest
    steps:
      - uses: mkimuram/test-gha/plugins/close@main
        with:
          repo: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue_num: ${{ github.event.client_payload.github.payload.issue.number }}
          pr_num: ${{ github.event.client_payload.pull_request.number }}
          token: ${{secrets.PAT}}
