# Usage: | `/assgin` | `/assign`<br> `/assign spongebob patrick` | Assigns assignee(s) to the PR. |
name: assign command
on:
  repository_dispatch:
    types: [assign-command]
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: mkimuram/test-gha/plugins/assign@main
        with:
          repo: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue_num: ${{ github.event.client_payload.github.payload.issue.number }}
          args: ${{ github.event.client_payload.slash_command.args.unnamed.all }}
          actor: ${{ github.actor }}
          token: ${{secrets.PAT}}
