# Usage: | `/reopen` | `/reopen` | Reopens an issue or PR. |
name: reopen command
on:
  repository_dispatch:
    types: [reopen-command]
jobs:
  reopen:
    runs-on: ubuntu-latest
    steps:
      - name: Reopen issue or pr
        run: |
          if [ -n "${PR_NUM}" ];then
            gh pr reopen "${PR_NUM}" -R ${REPO}
          else
            gh issue reopen ${ISSUE_NUM} -R ${REPO}
          fi
        env:
          REPO: ${{ github.event.client_payload.github.payload.repository.full_name }}
          ISSUE_NUM: ${{ github.event.client_payload.github.payload.issue.number }}
          PR_NUM: ${{ github.event.client_payload.pull_request.number }}
          GITHUB_TOKEN: ${{secrets.PAT}}
