# Usage: | `/retest` | `/retest` | Rerun test jobs that have failed. |
name: retest command
on:
  repository_dispatch:
    types: [retest-command]
jobs:
  retest:
    runs-on: ubuntu-latest
    steps:
      - name: Retest jobs
        run: |
          # TODO: make workflow_id auto detect and allow multiple ones
          workflow_id="test.yml"
          if [ -n "${SHA}" ];then
            run_id=$(gh api repos/${REPO}/actions/workflows/${workflow_id}/runs | \
              jq '.workflow_runs[] | select(.head_sha=="'${SHA}'") | .id')
            echo ${run_id}
            if [ -n "${run_id}" ];then
              # TODO: rerun only for failed jobs
              gh api repos/${REPO}/actions/runs/${run_id}/rerun -X POST
            fi
          fi
        env:
          REPO: ${{ github.event.client_payload.github.payload.repository.full_name }}
          SHA: ${{ github.event.client_payload.pull_request.head.sha }}
          GITHUB_TOKEN: ${{secrets.PAT}}

