# Usage: | `/kind` | `/kind bug` | Applies a kind label. |
name: kind command
on:
  repository_dispatch:
    types: [kind-command]
jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: mkimuram/test-gha/plugins/kind@main
        with:
          repo: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue_num: ${{ github.event.client_payload.github.payload.issue.number }}
          args: ${{ github.event.client_payload.slash_command.args.unnamed.all }}
          token: ${{secrets.PAT}}
