# Usage: | `/reopen` | `/reopen` | Reopens an issue or PR. |
name: reopen command
on:
  repository_dispatch:
    types: [reopen-command]
jobs:
  reopen:
    runs-on: ubuntu-latest
    steps:
      - uses: mkimuram/test-gha/plugins/reopen@main
        with:
          repo: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue_num: ${{ github.event.client_payload.github.payload.issue.number }}
          pr_num: ${{ github.event.client_payload.pull_request.number }}
          token: ${{secrets.PAT}}
