# Usage: | `/woof` | `/woof` | Add a dog image to the issue or PR. |
name: woof command
on:
  repository_dispatch:
    types: [woof-command]
jobs:
  woof:
    runs-on: ubuntu-latest
    steps:
      - uses: mkimuram/test-gha/plugins/woof@main
        with:
          repo: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue_num: ${{ github.event.client_payload.github.payload.issue.number }}
          pr_num: ${{ github.event.client_payload.pull_request.number }}
          token: ${{secrets.PAT}}
