# Usage: | `/meow` | `/meow` | Add a cat image to the issue or PR. |
name: meow command
on:
  repository_dispatch:
    types: [meow-command]
jobs:
  meow:
    runs-on: ubuntu-latest
    steps:
      - uses: mkimuram/test-gha/plugins/meow@main
        with:
          repo: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue_num: ${{ github.event.client_payload.github.payload.issue.number }}
          pr_num: ${{ github.event.client_payload.pull_request.number }}
          token: ${{secrets.PAT}}
