# Usage: | `/kind` | `/kind bug` | Applies a kind label. |
name: kind command
on:
  repository_dispatch:
    types: [kind-command]
jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - name: Add kind label to issue or pr
        run: |
          # args should not be empty
          [ -n "${ARGS}" ] || false
          # args should only contain one value
          [[ "${ARGS}" != *" "* ]] || false
          label="kind/${ARGS}"
          echo "{\"labels\":[\"${label}\"]}" | \
                gh api repos/${REPO}/issues/${ISSUE_NUM}/labels -X POST --input -
        env:
          REPO: ${{ github.event.client_payload.github.payload.repository.full_name }}
          ISSUE_NUM: ${{ github.event.client_payload.github.payload.issue.number }}
          ARGS: ${{ github.event.client_payload.slash_command.args.unnamed.all }}
          GITHUB_TOKEN: ${{secrets.PAT}}
