# Usage: | `/retest` | `/retest` | Rerun test jobs that have failed. |
name: retest command
on:
  repository_dispatch:
    types: [retest-command]
jobs:
  retest:
    runs-on: ubuntu-latest
    steps:
      - uses: mkimuram/test-gha/plugins/retest@main
        with:
          repo: ${{ github.event.client_payload.github.payload.repository.full_name }}
          sha: ${{ github.event.client_payload.pull_request.head.sha }}
          token: ${{secrets.PAT}}
