# Usage: | `/assgin` | `/assign`<br> `/assign spongebob patrick` | Assigns assignee(s) to the PR. |
name: assign command
on:
  repository_dispatch:
    types: [assign-command]
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: mkimuram/test-gha/plugins/assign@main
