name: Test
on:
  pull_request:
    branches: [ main ]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make unit-test

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make build
